name: Identifier Name
on:
  push:
    branches: [main]
jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - name: Reset Permissions before deployment
        uses: appleboy/ssh-action@master
        with:
          host: 18.188.3.76
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo chmod -R 755 /var/www/html/html2/
            sudo chown -R ubuntu:ubuntu /var/www/html/html2/
            sudo setfacl -R -m u:www-data:rwx /var/www/html/html2/
      - uses: actions/checkout@v2    
      - name: Deploy source-code
        uses: appleboy/scp-action@master
        env:
          HOST: 18.188.3.76
          USERNAME: ubuntu
          PORT: 22
          KEY: ${{ secrets.SSH_KEY }}
        with:
          source: "*"
          target: "/var/www/html/html2/"

      - name: Reset Permissions after deployment
        uses: appleboy/ssh-action@master
        with:
          host: 18.188.3.76
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo chmod -R 755 /var/www/html/html2/
            sudo chown -R www-data:www-data /var/www/html/html2/
            sudo setfacl -R -m u:ubuntu:rwx /var/www/html/html2/
